### ISSUE TITLE
Support Sony PS5 and FreeBSD 12.1 (vulkan backend)?

### ISSUE THREAD

**Issue by zoujiaqing** [egorodet/MethaneKit#70]

**Comment by egorodet** [comment]
@zoujiaqing Could you please describe in more details your particular need for PS5 and FreeBSD support in the cross-api framework like Methane Kit? Are you developing a game or game ending targeting specific platforms and APIs?

Vulkan backend implementation is planned for near future (covered by issue #10), but I'm not sure about gaming console support, which is out of scope of this project.

**Comment by egorodet** [comment]
Closing the issue, as there are no plans for direct support of gaming consoles, while Vulkan API support is already planned with issue #10.
